"""baseline

Revision ID: 5eb096cebe84
Revises: 
Create Date: 2026-04-04 10:39:27.689502
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb096cebe84'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('approval_id', sa.CHAR(length=36), nullable=False),
    sa.Column('request_id', sa.CHAR(length=36), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('policy_evaluation', sa.JSON(), nullable=False),
    sa.Column('capability_fingerprint', sa.String(), nullable=True),
    sa.Column('policy_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('webhook_delivery_status', sa.String(), nullable=False),
    sa.Column('webhook_delivery_attempts', sa.Integer(), nullable=False),
    sa.Column('webhook_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_last_response_code', sa.Integer(), nullable=True),
    sa.Column('webhook_last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approval_requests_agent_id'), 'approval_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_request_id'), 'approval_requests', ['request_id'], unique=True)
    op.create_table('approval_webhook_outbox',
    sa.Column('outbox_id', sa.CHAR(length=36), nullable=False),
    sa.Column('approval_id', sa.CHAR(length=36), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('outbox_id')
    )
    op.create_index(op.f('ix_approval_webhook_outbox_approval_id'), 'approval_webhook_outbox', ['approval_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('audit_id', sa.CHAR(length=36), nullable=False),
    sa.Column('request_id', sa.CHAR(length=36), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('policy_decision', sa.Enum('ALLOW', 'DENY', 'APPROVAL_REQUIRED', 'SANDBOX', 'QUARANTINE', name='decision'), nullable=False),
    sa.Column('final_decision', sa.Enum('ALLOW', 'DENY', 'APPROVAL_REQUIRED', 'SANDBOX', 'QUARANTINE', name='decision'), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.Column('approval_id', sa.CHAR(length=36), nullable=True),
    sa.Column('replayed_from_approval_id', sa.CHAR(length=36), nullable=True),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('auth_subject', sa.String(), nullable=True),
    sa.Column('auth_token_id', sa.String(), nullable=True),
    sa.Column('auth_key_id', sa.String(), nullable=True),
    sa.Column('chain_prev_hash', sa.String(), nullable=True),
    sa.Column('chain_hash', sa.String(), nullable=True),
    sa.Column('sandbox_id', sa.String(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_records_agent_id'), 'audit_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_records_approval_id'), 'audit_records', ['approval_id'], unique=False)
    op.create_index(op.f('ix_audit_records_auth_token_id'), 'audit_records', ['auth_token_id'], unique=False)
    op.create_index(op.f('ix_audit_records_chain_hash'), 'audit_records', ['chain_hash'], unique=False)
    op.create_index(op.f('ix_audit_records_replayed_from_approval_id'), 'audit_records', ['replayed_from_approval_id'], unique=False)
    op.create_index(op.f('ix_audit_records_request_id'), 'audit_records', ['request_id'], unique=False)
    op.create_table('capability_manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('namespace', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_manifests_agent_id'), 'capability_manifests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_capability_manifests_namespace'), 'capability_manifests', ['namespace'], unique=False)
    op.create_index(op.f('ix_capability_manifests_tenant_id'), 'capability_manifests', ['tenant_id'], unique=False)
    op.create_table('quota_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_events_agent_id'), 'quota_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_quota_events_created_at'), 'quota_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_quota_events_event_type'), 'quota_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_quota_events_tenant_id'), 'quota_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_quota_events_tool'), 'quota_events', ['tool'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_revoked_tokens_subject'), 'revoked_tokens', ['subject'], unique=False)
    op.create_table('sandbox_executions',
    sa.Column('sandbox_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.CHAR(length=36), nullable=False),
    sa.Column('approval_id', sa.CHAR(length=36), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('executor', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sandbox_id')
    )
    op.create_index(op.f('ix_sandbox_executions_agent_id'), 'sandbox_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sandbox_executions_approval_id'), 'sandbox_executions', ['approval_id'], unique=False)
    op.create_index(op.f('ix_sandbox_executions_request_id'), 'sandbox_executions', ['request_id'], unique=False)
    op.create_table('signing_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signing_keys')
    op.drop_index(op.f('ix_sandbox_executions_request_id'), table_name='sandbox_executions')
    op.drop_index(op.f('ix_sandbox_executions_approval_id'), table_name='sandbox_executions')
    op.drop_index(op.f('ix_sandbox_executions_agent_id'), table_name='sandbox_executions')
    op.drop_table('sandbox_executions')
    op.drop_index(op.f('ix_revoked_tokens_subject'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_quota_events_tool'), table_name='quota_events')
    op.drop_index(op.f('ix_quota_events_tenant_id'), table_name='quota_events')
    op.drop_index(op.f('ix_quota_events_event_type'), table_name='quota_events')
    op.drop_index(op.f('ix_quota_events_created_at'), table_name='quota_events')
    op.drop_index(op.f('ix_quota_events_agent_id'), table_name='quota_events')
    op.drop_table('quota_events')
    op.drop_index(op.f('ix_capability_manifests_tenant_id'), table_name='capability_manifests')
    op.drop_index(op.f('ix_capability_manifests_namespace'), table_name='capability_manifests')
    op.drop_index(op.f('ix_capability_manifests_agent_id'), table_name='capability_manifests')
    op.drop_table('capability_manifests')
    op.drop_index(op.f('ix_audit_records_request_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_replayed_from_approval_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_chain_hash'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_auth_token_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_approval_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_agent_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_approval_webhook_outbox_approval_id'), table_name='approval_webhook_outbox')
    op.drop_table('approval_webhook_outbox')
    op.drop_index(op.f('ix_approval_requests_request_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_agent_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
